# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Config USB
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_BOOT=y

# Knob configuration
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# OLED related configuration (Native ZMK Main)
CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_EXT_POWER=y

# Sleep related configuration
# Milliseconds of inactivity before entering idle state (10 minutes)
CONFIG_ZMK_IDLE_TIMEOUT=600000
# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# ZMK Studio configuration (Descomentado para activar soporte nativo)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# RGB related configuration
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_BACKLIGHT=n
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60

# Bluetooth stability (Actualizado para el nuevo upstream)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y